config/routes.rb
Rails.application.routes.draw do
  root 'posts#home'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = ('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def home
    if logged_in?
      @post = current_user.posts.build
    end
  end

  def new
    @post = current_user.posts.build if logged_in?
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to user_path(current_user.id)
  end

  def create
    @post = current_user.posts.build(post_params)
    @user = @post.user
    if @post.save
      flash[:success] = "Posted successfully!"
      redirect_to (user_url(@user.id))
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  def confirm 
    @post = current_user.posts.new(post_params)
     if @post.invalid?
      flash.now[:danger] = "contents and image must be filled in!"
      render 'new'
     end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Sign inに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, ]
  before_action :correct_user, only:[:edit, :update]

  def index
    @users = User.all
  end
  

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the kaobook"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to new_session_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path 
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user && user == current_user
  end
  
  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",'#' %></li>
      <li><%= link_to "Contact",'#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "kaobook", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", session_path(current_user.id), method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/confirm.html.erb
<h3> Confirm before post </h3>
<%= form_with(model:@post, url:posts_path, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="confirm-img">
        <%= image_tag(@post.image.url, size: '200x200') if @post.image.url %>
      </div>
      <%= f.hidden_field :image_cache %>
      <%= f.hidden_field :content %>
      <%= f.submit "Post", class: "btn btn-primary" %>
    </div>
   </div>
<% end %>

<%= form_with(model:@post, url:new_post_path, local:true, method: "get") do |f| %>
  <div class="row">
     <div class="col-md-6 col-md-offset-3">
      <%= f.hidden_field :iamge_cache %>
      <%= f.submit "戻る", name: "back", class: "btn btn-danger"%>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit your post</h3>
<%= form_with(model: @post, local: true) do |f| %>
  <div class="row">
     <div class="col-md-6 col-md-offset-3">
      <%= f.label :content %>
      <%= f.text_area :content,  class: 'form-control' %>
      <%= f.label :image %>
      <%= f.file_field :image,class: 'form-control' %>
      <%= f.submit "Post", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/home.html.erb
<div class="center jumpbotron">
<h1>Welcome to kaobook</h1>
<h2>This is the home page for kaobook</h2>
<%= link_to "Sign up", new_user_path, class:"btn btn-lg btn-primary" %>
</div>

app/views/posts/new.html.erb
<h1>新しく投稿する</h1>
<%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |f| %>
  <%= render 'shared/post_error_msg' %>
  <div class="row">
     <div class="col-md-6 col-md-offset-3">
      <%= f.label :content %>
      <%= f.text_area :content, placeholder: "Compose new post...", class: 'form-control'%>
      <%= f.label :image %>
      <%= f.file_field :image,class: 'form-control' %>
      <%= f.submit "Post", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Contents:</strong>
  <p><%= @post.content %></p>
  <%= image_tag @post.image.url, size: '200x200' %>
</p>

<%= link_to 'edit', edit_post_path(@post.id), class: 'btn btn-info' %>
<%= link_to 'back', user_path(current_user.id), class: 'btn btn-danger' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/shared/_post_error_msg.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
 <%= render 'shared/error_messages', object:@user %>

 <%= f.label :name %>
 <%= f.text_field :name, class: 'form-control' %>

 <%= f.label :email %>
 <%= f.email_field :email, class: 'form-control' %>

 <%= f.label :password %>
 <%=f.password_field :password, class: 'form-control' %>

 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation, class: 'form-control' %>

 <%= f.submit yield(:button_text), class: "btn btn-primary" %>
 <% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
<h1>Update your profile</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= gravatar_for user %>
    <%= link_to user.name, user %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= link_to "Create New Post", new_post_path, class: 'btn btn-primary' %>
      </section>
    </aside>
        <table class = "table table-striped">
          <thead>
            <strong><th>My post</th></strong>
            <tr> 
              <th>content</th>
              <th>image</th>
            </tr>
          </thead>
          <tbody>
            <% @user.posts.each do |post| %>
            <tr>
              <td><%= post.content %></td>
              <td><%= image_tag post.image.url, size: '70x70' %></td>
              <% if current_user?(post.user)  %>
                <td><%= link_to "detail", post, class: 'btn btn-warning' %></td>
                <td><%= link_to "edit", edit_post_path(post.id),  class: 'btn btn-info' %></td>
                <td><%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } ,class:'btn btn-danger' %></td>
              <% end %> 
            <% end %>    
            </tr>
          </tbody>
        </table>
  </div>
<% else %>
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<% end %>